using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Models;
using SakuraMod.SakuraModCode.Cards;
using System.Reflection;
using System.Text.Json.Nodes;

public sealed class GeneratedCardLifecycleSuite
{
    [Fact]
    public void VanillaGenerationEligibilityExcludesConversionAndSpellCards()
    {
        RegressionTestHarness.Require(
            !new SakuraRain().CanBeGeneratedInCombat,
            "Expected Classic Sakura conversion cards not to be generated by vanilla combat effects.");
        RegressionTestHarness.Require(
            new ClowRain().CanBeGeneratedInCombat,
            "Expected Classic Clow cards to remain valid vanilla combat generation options.");
        RegressionTestHarness.Require(
            !new SpellTurn().CanBeGeneratedInCombat,
            "Expected Spell Turn not to be generated by vanilla combat effects.");
        RegressionTestHarness.Require(
            !new SpellHuoShen().CanBeGeneratedInCombat,
            "Expected Classic Spell cards not to be generated by vanilla combat effects.");

    }

    [Fact]
    public void GeneratedCopyOptionsEncodeTemporaryAndRememberedSemantics()
    {
        var temporaryCopy = SakuraGeneratedCardLifecycle.TemporaryCopyOptions(freeThisTurn: true);
        RegressionTestHarness.Require(temporaryCopy.AddTemporary, "Expected temporary copy to add Temporary.");
        RegressionTestHarness.Require(!temporaryCopy.PreventTemporaryMemoryReturn, "Expected ordinary Temporary copies to enter Memory.");
        RegressionTestHarness.Require(temporaryCopy.FreeThisTurn, "Expected temporary copy to honor free-this-turn.");

        var rememberedCopy = SakuraGeneratedCardLifecycle.RememberedCopyOptions(
            freeThisTurn: true,
            addTemporary: false);
        RegressionTestHarness.Require(rememberedCopy.RemoveTemporary, "Expected remembered copy to remove stale Temporary.");
        RegressionTestHarness.Require(rememberedCopy.RemoveManifestAtlasOrigin, "Expected remembered copies to remove stale Manifest origin.");
        RegressionTestHarness.Require(!rememberedCopy.AddTemporary, "Expected remembered copy to avoid Temporary unless requested.");
        RegressionTestHarness.Require(!rememberedCopy.PreventTemporaryMemoryReturn, "Expected non-Temporary remembered copies not to need a Memory exception.");
        RegressionTestHarness.Require(rememberedCopy.FreeThisTurn, "Expected remembered copy to honor free-this-turn.");

        var temporaryRememberedCopy = SakuraGeneratedCardLifecycle.RememberedCopyOptions(
            freeThisTurn: true,
            addTemporary: true);
        RegressionTestHarness.Require(
            temporaryRememberedCopy.AddTemporary
            && temporaryRememberedCopy.PreventTemporaryMemoryReturn,
            "Expected Remind's Temporary copies to leave combat instead of returning to Memory.");

    }

    [Fact]
    public void MemorySelectionRejectsStaleAndDuplicateRecordsAtomically()
    {
        var firstSpiralRecord = new Spiral();
        var secondSpiralRecord = new Spiral();
        var records = new List<CardModel>
        {
            firstSpiralRecord,
            secondSpiralRecord
        };
        SakuraMemoryPile.ValidateSelection(records, [firstSpiralRecord]);

        var staleRecord = new Spiral();
        RegressionTestHarness.RequireThrows<InvalidOperationException>(
            () => SakuraMemoryPile.ValidateSelection(records, [secondSpiralRecord, staleRecord]),
            "Expected a stale memory selection to be rejected atomically.");
        RegressionTestHarness.Require(
            records.Count == 2
            && ReferenceEquals(records[0], firstSpiralRecord)
            && ReferenceEquals(records[1], secondSpiralRecord),
            "Expected Memory validation not to mutate the available records.");
        RegressionTestHarness.RequireThrows<InvalidOperationException>(
            () => SakuraMemoryPile.ValidateSelection(records, [secondSpiralRecord, secondSpiralRecord]),
            "Expected the same memory record not to be selected twice.");
    }

    [Fact]
    public void RemindUsesFixedRecallCountAndUpgradesFromTwoToThree()
    {
        var remind = new Remind();
        var upgradedRemind = RegressionTestHarness.MutableForCostTest(new Remind());
        upgradedRemind.UpgradeInternal();
        var spiral = new Spiral();
        var recallChoices = Remind.RecallChoices([new SpellTurn(), spiral]);
        RegressionTestHarness.Require(
            remind.EnergyCost.Canonical == 1
            && !remind.EnergyCost.CostsX
            && remind.DynamicVars.Cards.IntValue == 2
            && upgradedRemind.DynamicVars.Cards.IntValue == 3
            && recallChoices.Count == 1
            && ReferenceEquals(recallChoices[0], spiral),
            "Expected Remind to cost 1, recall 2/3 eligible cards, and exclude Turn from Memory choices.");
    }

    [Fact]
    public void TemporaryMemoryReturnRulePersistsAndCleanupExcludesExhaust()
    {
        var original = new TemporaryModifier();
        original.PreventMemoryReturn();
        var save = (JsonNode?)typeof(TemporaryModifier)
            .GetMethod("SaveAdditionalState", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.DeclaredOnly)!
            .Invoke(original, null);

        var restored = new TemporaryModifier();
        typeof(TemporaryModifier)
            .GetMethod("LoadAdditionalState", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.DeclaredOnly)!
            .Invoke(restored, [save, 1]);
        var legacy = new TemporaryModifier();
        typeof(TemporaryModifier)
            .GetMethod("LoadAdditionalState", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.DeclaredOnly)!
            .Invoke(legacy, [null, 1]);

        RegressionTestHarness.Require(
            !restored.ReturnsToMemory && legacy.ReturnsToMemory,
            "Expected the Remind no-return exception to persist while missing legacy state defaults to ordinary Memory return.");
        RegressionTestHarness.Require(
            TemporaryModifier.CleanupPileTypes.SequenceEqual(
                [PileType.Hand, PileType.Play, PileType.Discard, PileType.Draw]),
            "Expected Temporary cleanup to scan active vanilla combat piles in deterministic order without moving cards out of Exhaust.");
    }
}
