<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\Sts2PathDiscovery.props" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>true</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GodotProjectDir>$(MSBuildProjectDirectory)/../</GodotProjectDir>
  </PropertyGroup>

  <ItemGroup>
    <CompilerVisibleProperty Include="GodotProjectDir" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageReference Include="STS2.RitsuLib.Compat.0.107.1" Version="0.5.15" PrivateAssets="All" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" PrivateAssets="All" />
    <Reference Include="sts2">
      <HintPath>$(Sts2DataDir)/sts2.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(Sts2DataDir)/0Harmony.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../SakuraMod.csproj" />
    <ProjectReference Include="../tests/SakuraMod.TestRunner/SakuraMod.TestRunner.csproj" />
  </ItemGroup>
</Project>
